version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:fpm
        volumes:
            - ./code:/code
        networks:
            - code-network
    db:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: db
            MYSQL_ROOT_PASSWORD: dbpswd
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: dbpswd
        ports:
          - "4306:3306"

networks:
    code-network:
        driver: bridge

volumes:
    db_data: