version: '2'
services:
    app:
        build:
            context: ./
            dockerfile: app.dockerfile
        working_dir: /var/www
        volumes:
            - ./:/var/www
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=db"
    web:
        build:
            context: ./
            dockerfile: web.dockerfile
        working_dir: /var/www
        volumes_from:
            - app
        ports:
            - 8080:80

    db:
        image: mysql:5.7
            environment:
                MYSQL_DATABASE: db
                MYSQL_ROOT_PASSWORD: dbpswd
                MYSQL_USER: dbuser
                MYSQL_PASSWORD: dbpswd
            ports:
                - "4306:3306"
volumes:
    dbdata:
